# Generated by Django 5.1.1 on 2024-09-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(verbose_name='Tipo de preferência')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Preferência',
                'verbose_name_plural': 'Preferências',
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome do ponto turístico')),
                ('descricao', models.TextField(verbose_name='Descrição do ponto turístico')),
                ('localizacao', models.CharField(max_length=1500, verbose_name='Localização')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('preferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.preferencias', verbose_name='Preferência')),
            ],
        ),
    ]
