# Generated by Django 5.1.1 on 2024-10-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_preferencias_estadio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do estadio'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome do estadio'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise', models.TextField(verbose_name='Análise')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadio', verbose_name='Estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data do evento')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadio', verbose_name='Estádio')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do time')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('estadio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estadio', verbose_name='Estádio')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('preferencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.preferencias', verbose_name='Preferências')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
            },
        ),
    ]
