# Generated by Django 5.0.7 on 2024-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_options_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, default='app/static/imagens/avatar.png', upload_to='app/static/imagens'),
        ),
    ]
