# Generated by Django 5.1.2 on 2024-10-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_avaliacao_estrelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadio',
            name='preferencia',
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estadio_imagens/'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='localizacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
