# Generated by Django 5.1.2 on 2024-10-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_avaliacao_estrelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresso',
            old_name='data',
            new_name='data_evento',
        ),
    ]
