# Generated by Django 5.1.2 on 2024-10-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_data_ingresso_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='tipo',
            field=models.CharField(choices=[('meia', 'Meia-entrada'), ('inteira', 'Inteira')], default='inteira', max_length=7, verbose_name='Tipo de Ingresso'),
        ),
    ]
