# Generated by Django 5.1.2 on 2024-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_ingresso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='historia',
            field=models.TextField(blank=True, help_text='Escreva a história do time', null=True),
        ),
    ]
