# Generated by Django 5.1.2 on 2024-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_time_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='historia',
        ),
        migrations.AddField(
            model_name='time',
            name='titulos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
