# Generated by Django 5.0.3 on 2024-10-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_time_historia_time_titulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roteiro',
            name='preferencias',
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.time'),
        ),
    ]
