# Generated by Django 5.0.3 on 2024-10-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_roteiro_preferencias_alter_roteiro_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='estadio',
            options={'verbose_name': 'Estádio', 'verbose_name_plural': 'Estádios'},
        ),
        migrations.AlterField(
            model_name='estadio',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estadio_imagens/', verbose_name='Imagem do Estádio'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='localizacao',
            field=models.CharField(max_length=200, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do estádio'),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='brasao',
            field=models.ImageField(blank=True, help_text='Carregue o brasão do time', null=True, upload_to='brasoes/', verbose_name='Brasão'),
        ),
        migrations.AlterField(
            model_name='time',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='time',
            name='estadio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estadio', verbose_name='Estádio'),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='titulos',
            field=models.TextField(blank=True, null=True, verbose_name='Títulos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, default='imagens/avatar.png', upload_to='imagens/', verbose_name='Imagem do Usuário'),
        ),
    ]
