# Generated by Django 5.0.3 on 2024-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_avaliacao_options_alter_estadio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roteiro',
            name='time',
        ),
        migrations.AddField(
            model_name='roteiro',
            name='preferencias',
            field=models.CharField(default='', max_length=255),
        ),
    ]
