# Generated by Django 5.0.3 on 2024-10-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_roteiro_time_roteiro_preferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='preferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.preferencias', verbose_name='Preferência'),
        ),
    ]
