# Generated by Django 5.0.3 on 2024-10-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_estadio_preferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='preferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.preferencias', verbose_name='Preferência'),
        ),
    ]
