# Generated by Django 5.0.3 on 2024-10-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_estadio_preferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadio',
            name='preferencia',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Preferencias',
        ),
        migrations.DeleteModel(
            name='Roteiro',
        ),
    ]
