# Generated by Django 5.0.3 on 2024-10-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_preferencias_roteiro_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome do ponto turístico')),
                ('descricao', models.TextField(verbose_name='Descrição do ponto turístico')),
                ('localizacao', models.CharField(max_length=1500, verbose_name='Localização')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('preferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.preferencias', verbose_name='Preferência')),
            ],
        ),
    ]
