# Generated by Django 5.1.1 on 2024-09-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.AlterModelOptions(
            name='ingresso',
            options={'verbose_name_plural': 'Ingressos'},
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Ingresso',
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fundacao', models.DateField()),
                ('localizacao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='static/')),
                ('ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingresso')),
            ],
            options={
                'verbose_name_plural': 'Estádios',
            },
        ),
    ]
